spring.application.name=teaDelivery

#Data Source Properties
spring.datasource.driverClassName = org.postgresql.Driver
spring.datasource.url = jdbc:postgresql://localhost:5432/TeaDelivery
spring.datasource.username = postgres
spring.datasource.password = 1234

#JPA Properties
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql = FALSE
spring.jpa.properties.hibernate.show_sql = FALSE
spring.jpa.hibernate.ddl-auto = create

#Disable the default loggers
logging.level.org = WARN
logging.level.blog = WARN

#Show SQL executed with parameter bindings
#logging.level.org.hibernate.SQL = DEBUG
logging.level.org.hibernate.SQL = OFF
logging.level.org.hibernate.type.descriptor = TRACE

app.default.password: topsecret

#Redis
#spring.data.redis.host=localhost
#spring.data.redis.port=6379
spring.redis.host=localhost
spring.redis.port=6379
#spring.main.allow-bean-definition-overriding=true

#elasticsearch
spring.elasticsearch.uris=http://localhost:9200
spring.elasticsearch.connection-timeout=5000
spring.elasticsearch.socket-timeout=3000
logging.file.path=C:\\logs\\
logging.level.root=warn
logging.level.org.springframework=INFO